src/App/TestBundle/Entity/AuthUser.php
<?php

namespace App\TestBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Security\Core\User\UserInterface;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * App\TestBundle\Entity\AuthUser
 */
class AuthUser implements UserInterface
{
    /**
     * @var integer $authUserId
     */
    private $authUserId;

    /**
     * @var string $username
     * 
     * @Assert\NotBlank()
     */
    private $username;

    /**
     * @var string $salt
     */
    private $salt;

    /**
     * @var string $password
     */
    private $password;

    /**
     * @var App\TestBundle\Entity\AuthRole
     */
    private $authRole;


    /**
     * Get authUserId
     *
     * @return integer 
     */
    public function getAuthUserId()
    {
        return $this->authUserId;
    }

    /**
     * Set username
     *
     * @param string $username
     */
    public function setUsername($username)
    {
        $this->username = $username;
    }

    /**
     * Get username
     *
     * @return string 
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set salt
     *
     * @param string $salt
     */
    public function setSalt($salt)
    {
        $this->salt = $salt;
    }

    /**
     * Get salt
     *
     * @return string 
     */
    public function getSalt()
    {
        return $this->salt;
    }

    /**
     * Set password
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password = $password;
    }

    /**
     * Get password
     *
     * @return string 
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set authRole
     *
     * @param App\TestBundle\Entity\AuthRole $authRole
     */
    public function setAuthRole(\App\TestBundle\Entity\AuthRole $authRole)
    {
        $this->authRole = $authRole;
    }

    /**
     * Get authRole
     *
     * @return App\TestBundle\Entity\AuthRole 
     */
    public function getAuthRole()
    {
        return $this->authRole;
    }



    public function getRoles()
    {
//        return array('ROLE_ADMIN');
	return array($this->authRole->getName());
    }

    public function eraseCredentials()
    {
        
    }

    public function equals(UserInterface $user)
    {
        return $this->getUsername() == $user->getUsername();
    }

    /**
     * @var string $aaa
     */
    private $aaa;


    /**
     * Set aaa
     *
     * @param string $aaa
     */
    public function setAaa($aaa)
    {
        $this->aaa = $aaa;
    }

    /**
     * Get aaa
     *
     * @return string 
     */
    public function getAaa()
    {
        return $this->aaa;
    }
}

src/App/TestBundle/Controller/UserController.php
<?php
namespace App\TestBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use App\TestBundle\Entity\AuthUser;
use App\TestBundle\Form\Type\AuthUserType;
use App\TestBundle\Form\Data\AuthUserFormData;
use App\TestBundle\Lib\AuthenticationMng;
use Symfony\Component\HttpFoundation\Response;

class UserController  extends Controller
{

    public function listAction()
    {
//        $users = $this->getDoctrine()->getRepository('AppTestBundle:AuthUser')->findAll();
        $em = $this->get('doctrine.orm.entity_manager');
        $dql = "SELECT a FROM AppTestBundle:AuthUser a";
        $query = $em->createQuery($dql);

        //pagerオブジェクト取得
        $paginator = $this->get('knp_paginator');
        $users = $paginator->paginate(
            $query,
            $this->get('request')->query->get('page', 1)/*page number*/,
            3/*limit per page*/
        );
        
        return $this->render('AppTestBundle:User:list.html.twig', array('users' => $users));
    }
    
    public function createAction(Request $request)
    {
        //
        $authuser = new AuthUser();

        //formクラスとformdataクラスを使用するパターン
//        $authuser_form = new AuthUserFormData();
        $authuser_form = $this->get('form.data.auth_user_form_data');
        $form = $this->createForm(new AuthUserType(), $authuser_form);
        
/*        
        //formクラスを使用するパターン
        $form = $this->createForm(new AuthUserType(), $authuser);
*/
/*
        //createFormBuilderを使用するパターン
        $form = $this->createFormBuilder($authuser)
                ->add('username', 'text')
                ->add('password', 'password')
                ->add('authrole', 'entity', array(
                    'class' => 'App\TestBundle\Entity\AuthRole',
                    'property' => 'name',
                ))
                ->getForm();
*/
       
        //
        if ($request->getMethod() === 'POST')
        {
            $form->bindRequest($request);
            if($form->isValid())
            {
                //formデータ取得
                $formdata = $form->getData();
                
                //保存
                $em = $this->get('doctrine')->getEntityManager();
                $auth_mng = new AuthenticationMng($em);
                $auth_mng->insertUserForm($formdata);
                
/*
                //
                $authuser->setUsername($formdata->getUsername());
                $authuser->setPassword($formdata->getPassword());
                $authuser->setSalt('');
                $authuser->setAuthRole($formdata->getAuthRole());
                
                //
                $em = $this->getDoctrine()->getEntityManager();
                $em->persist($authuser);
                $em->flush();
*/
            }
        }

        return $this->render('AppTestBundle:User:create.html.twig', array('form' => $form->createView()));
    }
    
    public function checkUserName(Request $request)
    {
        $ret = array('result' => false, 'data' => array());
        //
        if ($request->getMethod() === 'POST' && $request->get('username') != null)
        {
            $authmng = $this->get('asauth.mng');
            if($authmng->isUsernameUnique($request->get('username')))
            {
                $ret['result'] = true;
                $ret['data']['isunique'] = true;
            }else
            {
                $ret['result'] = true;
                $ret['data']['isunique'] = false;
            }
        }else
        {
            $ret['result'] = false;
        }
        
        return $ret;
    }
    
    public function checkUserNameAction(Request $request)
    {
        $ret = $this->checkUserName($request);
        $return=json_encode($ret);
        return new Response($return, 200, array('Content-Type' => 'application/json; charset=utf-8'));
    }
    
    public function checkUserNameAjaxAction(Request $request)
    {
        $ret = $this->checkUserName($request);
        if(!$ret['result'])
        {
            return new Response();
        }
        return $this->render('AppTestBundle:User:ajax_check_username.html.twig', array('result' => $ret));
    }
    
}

?>

src/App/TestBundle/Resources/views/User/ajax_check_username.html.twig

{% if result.data.isunique == true %}
OK!!
{% else %}
NG!!
{% endif %}

src/App/TestBundle/Resources/views/User/create.html.twig
{% extends '::base.html.twig' %}

{% block javascripts %}
    <script src="{{ asset('js/jquery-1.7.2.min.js') }}"></script>
    {% block page_javascript %}{% endblock page_javascript %}
    <script type="text/javascript">
    <!--
    $(function(){
        $('#AuthUser_username').blur(function(){
            $.post(
                '{{ path('auth_mng_check_username_ajax') }}',
                {
                    'username': $('#AuthUser_username').val()
                },
                function(data){
                    $('#AuthUser_username_ajax_checkusername').text(data);
                }
            );
        });
    });
    // -->
    </script>
{% endblock %}

{# body #}
{% block body %}

<form action="{{ path('auth_mng_create') }}" method="post" {{ form_enctype(form) }} novalidate>

    {{ form_widget(form) }}

    <input type="submit" />
</form>

{% endblock %}

{# username row カスタマイズ #}
{% form_theme form _self %}
{% block _AuthUser_username_row %}
    <div>
        {{ form_label(form) }}
        {{ form_errors(form) }}
        {{ form_widget(form) }}
        <span id="AuthUser_username_checkusername"></span>
        <div id="AuthUser_username_ajax_checkusername"></div>
    </div>
{% endblock %}

src/App/TestBundle/Resources/views/User/list.html.twig
{% extends '::base.html.twig' %}

{% block body %}

<table>
    <tr>
        <td>id</td>
        <td>username</td>
        <td>password</td>
        <td>rols</td>
    </tr>

    {% for user in users %}
        <tr>
            <td>{{user.authUserId}}</td>
            <td>{{user.username}}</td>
            <td>{{user.password}}</td>
{#            <td>
            {% for role in user.roles %}
                {{role}}
            {% endfor %}
            </td>
#}
        </tr>
    {% endfor %}

</table>

{{ users.render()|raw }}

{% endblock %}

